### PR TITLE
MEGA REFACTOR AGAIN

### PR DESCRIPTION
**Pull request by kianenigma**

### CODE REVIEW

**Comment by kianenigma** [comment]
@alvicsam can you merge the conflicts here and merge this branch with the dockerfile that you prefer? 

This has all the new features integrated. Still needs a bit of work to update the README though. I will do that ASAP as well. 

The config format has changed a bit and now supports YAML as well.

**Comment by alvicsam** [comment]
@kianenigma it seems I need your help. `build` is not defined in `package.json` so when I run 
```
docker build . -t deleteme -f Containerfile
```

I have this error:

```
Step 13/26 : RUN npm run build
 ---> Running in 4abf4965a114
npm ERR! Missing script: "build"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2022-08-02T12_10_53_611Z-debug-0.log
```

**Comment by alvicsam** [comment]
I've tried to build it with `./node_modules/typescript/bin/tsc -b` and have a lot of errors: https://gitlab.parity.io/parity/mirrors/polkadot-basic-notification/-/jobs/1717665

This workaround however works but I'm not sure in the result that is built:
```
npm ci --ignore-scripts
./node_modules/typescript/bin/tsc || echo ok
./node_modules/typescript/bin/tsc -b
```

**Comment by kianenigma** [comment]
@alvicsam https://github.com/paritytech/polkadot-basic-notification/pull/5/commits/4da60206444a71804d86c136d7f740c0f4db6bc1 fixes this.

**Comment by alvicsam** [comment]
Thank you! I merged the changes in https://github.com/paritytech/polkadot-basic-notification/pull/6

**Pull request closed without merging**
